development:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAI3GIATIBLDOLYHGQ
  AWS_SECRET_ACCESS_KEY: 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

test:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAI3GIATIBLDOLYHGQ
  AWS_SECRET_ACCESS_KEY: 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

production:
   S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAI3GIATIBLDOLYHGQ
  AWS_SECRET_ACCESS_KEY: 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