development:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAJCLSMHZKRXXRMK7A
  AWS_SECRET_ACCESS_KEY: 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

test:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAJCLSMHZKRXXRMK7A
  AWS_SECRET_ACCESS_KEY: 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

production:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAJCLSMHZKRXXRMK7A
  AWS_SECRET_ACCESS_KEY: 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