development:
  S3_BUCKET_NAME: richrly-development
  AWS_ACCESS_KEY_ID: AKIAITYSYXKG4A5IJHZQ
  AWS_SECRET_ACCESS_KEY: 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

test:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAITYSYXKG4A5IJHZQ
  AWS_SECRET_ACCESS_KEY: 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

production:
  S3_BUCKET_NAME: richrly
  AWS_ACCESS_KEY_ID: AKIAITYSYXKG4A5IJHZQ
  AWS_SECRET_ACCESS_KEY: 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