development:
  KEY: 109366218276-2gbhjdc88f6fdbt2s2b3ccbfekhu2leu.apps.googleusercontent.com
  SECRET: vHg_4O6FvHQQf2irvEkD1MY7

test:
  KEY: 109366218276-2gbhjdc88f6fdbt2s2b3ccbfekhu2leu.apps.googleusercontent.com
  SECRET: vHg_4O6FvHQQf2irvEkD1MY7

production:
  KEY: 109366218276-2gbhjdc88f6fdbt2s2b3ccbfekhu2leu.apps.googleusercontent.com
  SECRET: vHg_4O6FvHQQf2irvEkD1MY7