development:
  KEY: 109366218276-2gbhjdc88f6fdbt2s2b3ccbfekhu2leu.apps.googleusercontent.com
  SECRET: AIzaSyADaIb1COLplGsBbl9HFBErP_Evdx2RvZU

test:
  KEY: 109366218276-2gbhjdc88f6fdbt2s2b3ccbfekhu2leu.apps.googleusercontent.com
  SECRET: AIzaSyADaIb1COLplGsBbl9HFBErP_Evdx2RvZU
  
production:
  KEY: 109366218276-2gbhjdc88f6fdbt2s2b3ccbfekhu2leu.apps.googleusercontent.com
  SECRET: AIzaSyADaIb1COLplGsBbl9HFBErP_Evdx2RvZU