development:
  KEY: Cn0DNY8lqhIhGEWM6pn3Cabui
  SECRET: d001AdP9dnY9sZzn8pQZfQp3oS6fOdzk9n0F0OPSNaPOiMasfd

test:
  KEY: Cn0DNY8lqhIhGEWM6pn3Cabui
  SECRET: d001AdP9dnY9sZzn8pQZfQp3oS6fOdzk9n0F0OPSNaPOiMasfd

production:
  KEY: Cn0DNY8lqhIhGEWM6pn3Cabui
  SECRET: d001AdP9dnY9sZzn8pQZfQp3oS6fOdzk9n0F0OPSNaPOiMasfd
