development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobantoniojha2
  password: b8f24b71-7cbf-4ed5-8ab9-26ba89aa8c8f
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobantoniojha2
  password: b8f24b71-7cbf-4ed5-8ab9-26ba89aa8c8f
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true