development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobantoniojha
  password: e385305e-5657-4217-93bf-7070c9e46431
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username:
  password:
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true