development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobjohndoe
  password: 1234abc5-1234-1ab2-a12c-e1ab23cdef4f
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username:
  password:
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true