development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobantoniojha3
  password: c7ac6d4e-0178-493c-bdcb-d8147eafbddf
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobantoniojha3
  password: c7ac6d4e-0178-493c-bdcb-d8147eafbddf
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true